In [13]:
import numpy as np

In [14]:
H = np.array([
    [0,0,0,1,1,1,1,0,1,0],
    [1,0,0,0,0,0,1,1,1,1],
    [1,1,1,0,1,1,1,0,0,1],
    [1,0,1,1,0,1,1,1,0,0]
]);

In [15]:
def generate(l):
    res = []
    
    for i in range(1, 2**l):
        b = bin(i)[2:]
        b = '0' * (l - len(b)) + b
        b = np.array(list(map(lambda x: int(x), b)))
        res.append(b)
        
    return np.array(res)

In [16]:
n = 10
k = 6
r = 4

a_s = generate(r)
a_e = generate(n)

In [17]:
def get_min(s):
    res = a_e.shape[1]
    for e in a_e:
        if np.all(s == (np.dot(e, H.T) % 2)):
            res = min(res, np.sum(e))
    return res


def get_syndrom_matrix():
    res = []
    for s in a_s:
        m = get_min(s)
        
        for e in a_e:
            if np.all(s == (np.dot(e, H.T) % 2)) and (np.sum(e) == m):
                res.append((s, e))
                break
    
    return res

In [18]:
mat = get_syndrom_matrix()
for l in mat:
    print(l[0], l[1])

[0 0 0 1] [0 0 0 0 0 0 0 1 0 0]
[0 0 1 0] [0 0 0 0 0 0 1 0 0 0]
[0 0 1 1] [0 0 0 0 0 0 0 0 1 0]
[0 1 0 0] [0 0 0 1 0 0 1 0 0 0]
[0 1 0 1] [0 1 0 0 0 0 0 0 0 0]
[0 1 1 0] [0 0 0 1 0 0 0 0 0 0]
[0 1 1 1] [0 0 0 0 1 0 0 0 0 1]
[1 0 0 0] [1 0 0 0 0 0 0 0 0 0]
[1 0 0 1] [0 0 0 0 1 0 0 0 0 0]
[1 0 1 0] [0 0 1 0 0 0 0 0 0 0]
[1 0 1 1] [0 0 0 0 1 0 1 0 0 0]
[1 1 0 0] [0 0 0 0 0 0 1 0 0 1]
[1 1 0 1] [0 0 0 0 0 0 0 0 1 1]
[1 1 1 0] [0 0 0 0 0 0 0 0 0 1]
[1 1 1 1] [0 0 0 0 0 1 0 0 0 0]
