In [2]:
import numpy as np

In [3]:
A1 = np.array([
    [1,0,1,1,0,0],
    [0,1,0,1,1,0],
    [0,0,1,0,1,1]
])
A1

array([[1, 0, 1, 1, 0, 0],
       [0, 1, 0, 1, 1, 0],
       [0, 0, 1, 0, 1, 1]])

In [4]:
H = np.array([
    [0,0,0,1,1,1,1],
    [0,1,1,0,0,1,1],
    [1,0,1,0,1,0,1]
])

In [5]:
c = np.array([1,0,1,1,0,1,0])
e = np.array([0,1,1,1,0,0,0])

In [6]:
np.dot((c + e), H.T) % 2

array([1, 0, 1])

In [7]:
H

array([[0, 0, 0, 1, 1, 1, 1],
       [0, 1, 1, 0, 0, 1, 1],
       [1, 0, 1, 0, 1, 0, 1]])

In [9]:
H = np.array([
    [0,0,0,1,1,1,1,0,1,0],
    [1,0,0,0,0,0,1,1,1,1],
    [1,1,1,0,1,1,1,0,0,1],
    [1,0,1,1,0,1,1,1,0,0]
]);
G = np.array([
    [0,0,0,0,0,0,1,1,1,1],
    [1,1,0,0,0,0,0,1,0,0],
    [0,0,1,0,0,0,1,0,1,0], 
    [0,0,0,1,0,0,0,1,1,0],
    [0,0,0,0,1,0,1,1,0,0],
    [1,0,0,0,0,1,0,0,1,0]
])

print(np.dot(G,H.T) % 2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
